version: "3"
services:
  client:
    build: ./services/client
    volumes:
      - ../service/web/client:/usr/src/twittersearch/client
    ports:
      - "3000:3000"
    container_name: twitter-search-client
    hostname: twitter-search-client
  server:
    build: ./services/server
    volumes:
      - ../service/web/server:/usr/src/twittersearch/server
    ports:
      - "8000:8000"
    container_name: twitter-search-server
    hostname: twitter-search-server
