version: "3"
services:
  client:
    build: ./services/client
    volumes:
      - ../service/client:/usr/src/twittersearch/client
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "3000:3000"
    container_name: twitter-search-client
    hostname: twitter-search-client
  server:
    build: ./services/server
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ../service/server:/usr/src/twittersearch/server
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "8000:8000"
    container_name: twitter-search-server
    hostname: twitter-search-server
    network_mode: "host"
    tty: true
    depends_on:
      - postgres
  postgres:
    build: ./services/postgres
    user: root
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "tweet"
    volumes:
      - /data/pgdata:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    ports:
      - "5432:5432"
    container_name: twitter-search-postgres
    hostname: twitter-search-postgres
    network_mode: "host"
